table A_Slicer
	lineageTag: da187f5b-1da4-4aaa-85cd-20addf8f8ed4

	column Col
		dataType: string
		lineageTag: 8e89cc48-6f25-4842-8a47-816d572c15af
		summarizeBy: none
		sourceColumn: Col

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Col2
		dataType: int64
		formatString: 0
		lineageTag: 0b746f59-f404-4c97-ab06-e80fda80e9db
		summarizeBy: sum
		sourceColumn: Col2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition A_Slicer-08c1baa9-2fbe-40af-9e2c-d5899fd93d9a = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45W8s3MU9JRMlSK1QGyEyuAbCMwOyS/JDEHyDMG85zzS/NKgDwTMM+xLLUoMT0VyDdVio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Col = _t, Col2 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Col", type text}, {"Col2", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

